### ISSUE TITLE
How to set brightness manually?

### ISSUE THREAD

**Issue by flleeppyy** [threethan/QuestHiddenSettings#1]
I'm on a Quest 1 and I can't open the brightness menu in Settings after clicking the minimum brightness button in your app. Trying to open the brightness menu crashes the settings app.

**Comment by flleeppyy** [comment]
I know that you can adjust it using `adb` but I'd like to have a brightness slider.

**Comment by threethan** [comment]
All the minimum brightness does it set it to zero, same as if you used adb.
I don't have a quest 1 so I can't test it. Try setting brightness to
different values through adb and see if it fixes it. I found that the
slider on the quest 2 goes from 22 to 100. When setting it with the app (on
quest 2) the slider doesn't update to reflect the new brightness, but it
still works just fine.
May I ask what software version you're on?
